### ISSUE TITLE
Is there a firmware update plan?

### ISSUE THREAD

**Issue by chenpeng198877** [valerionew/unisolder-notes#16]

**Comment by nicola-d** [comment]
I think the latest firmware can be found here:
http://dangerousprototypes.com/forum/index.php?topic=7218.msg70644#msg70644

**Comment by nicola-d** [comment]
In any case, the original firmware source code is always available in the first post of the thread.

**Comment by nicola-d** [comment]
And I think the original firmware is pretty much complete, as long as someone doesn't want to attach an unsupported iron/tip.

**Comment by chenpeng198877** [comment]
> 我认为可以在这里找到最新的固件：[http](http://dangerousprototypes.com/forum/index.php?topic=7218.msg70644#msg70644) :
> [//dangerousprototypes.com/forum/index.php?topic=7218.msg70644#msg70644](http://dangerousprototypes.com/forum/index.php?topic=7218.msg70644#msg70644)

It's unknown for what reason! Nothing happens after the firmware is flashed! 1106 1306oled are all the same

**Comment by valerionew** [comment]
Firmware is beeig now updated by the author in the new unisolder repo

Check it out at:
https://github.com/sparkybg/UniSolder-5.2

Closing as this is no longer relevant for this repo
