### ISSUE TITLE
Problems with calibration

### ISSUE THREAD

**Issue by curieos** [valerionew/unisolder-notes#18]
I'd post this to the forum, but I'm not getting the verification emails when I sign up, and no one has responded.

I'm trying to calibrate my unisolder. When I go into the calibration menu, the R value is sitting at 35 with the 10 ohm resistor attached. I can turn the trimmer and have it go up to 40, or down and it goes to 30. If I disconnect the resistor, the value shoots up to 1100-ish. Reading the docs, it is supposed to be close to 1000 with the 10 ohm resistor? I tried searching through the forums, but I didn't find anything that solved my issue. I found some things that mentioned the current across Sense A and Vout1- should be around 380uA, mine measures 360uA (though I don't fully trust my multimeter). I double checked U11 was soldered on properly, as well as the PIC, but I haven't been able to figure it out. I even replaced Rc2 thinking it was a broken pot (original spun infinitely).

**Comment by nicola-d** [comment]
I also had problems getting the verification email from the forum. After several tries I succeded though.

I don't remember much of the calibration procedure but I'm pretty sure it wasn't straightforward for me either. The values weren't the ones expected. I think I had to check and redo some solder joints to solve the problem...

**Comment by curieos** [comment]
I figured the problem out, for some reason two of the pins on U17 were shorted somehow. I was able to calibrate, but now I have a new issue. When I plug the iron in it says "Heater Open". I double checked the wiring and I'm pretty sure the connector is wired up correctly. I'll do some more searching on the forum.

**Comment by curieos** [comment]
When it said "Heater Open", the iron was correctly identified. I found a short on C17, resoldered it, and now it says "no instrument". I went into the calibration screen and the IDs are set to 5 and 5. I then found shorts on R2 and R21, fixed those, and the same issue is present. Not sure what is going on, I'll keep looking.

**Comment by nicola-d** [comment]
Maybe this is of some help:

http://dangerousprototypes.com/forum/index.php?topic=7218.msg68141#msg68141

**Comment by curieos** [comment]
The recommendation is to reprogram, but it looks like the problem was resolved by replacing the PIC... I'll do some more looking on the forum, maybe I'll find something where I don't have to replace the entire PIC and that will work...

**Comment by curieos** [comment]
I figured it out, turns out I did wire it incorrectly. Had heater channel two + and - flipped. Guess that's what I get for soldering while tired. That explains why it detected the iron before, C17 was shorting channel 2 + and - together...
