### ISSUE TITLE
Rotary Encoder information

### ISSUE THREAD

**Issue by wildstar87** [valerionew/unisolder-notes#37]
Was having a lot of problems getting a rotary encoder to work.  Finally found this note, buried in the thread.  Would be nice to put this into your notes so it's more easily found.

Information was found here in the main thread:
http://dangerousprototypes.com/forum/index.php?topic=7218.msg71747#msg71747

The control method is selected this way:
- go to menu
- press and hold center button ot encoder button for 5 seconds
- pres and release center button to select the control option
- leave it alone for 5 seconds and it will exit

The meaning of options:
- KEYS - the plain old 3 button control
- ENC-A-1PPD - encoder with channel A event, 1 pulse per detent
- ENC-AB-2PPD - encoder with channel A and channel B event, 2 pulses per detent (one for A and one for B)
- ENC-A-2PPD - encoder with channel A event, 2 pulses per detent
- ENC-AB-4PPD - encoder with channel A and channel B event, 4 pulses per detent (2 for A and 2 for B channel)

Just select what works best for you. The goal is to select an variant which leads to change of temperature/option with one up or one down per detent.

There is a connection picture here: http://dangerousprototypes.com/forum/index.php?topic=7218.msg74587#msg74587
![front2](https://github.com/valerionew/unisolder-notes/assets/54087228/b10d6969-8f16-4efb-a9bf-cb49df2b4c06)

**Comment by valerionew** [comment]
Thank you. I really think that would be useful, I didn't even know you could use a rotary encoder. Are you comfortable preparing a PR for adding that?

**Comment by wildstar87** [comment]
Not sure what a PR is in this case.
________________________________

**Comment by valerionew** [comment]
Pull request - modifying the file in the repository and submitting the modification to be inlcuded in the main page.

If you cannot do this, we can see if anyone wants to contribute

**Comment by wildstar87** [comment]
I made the PR, but never done it before, so let me know if I screwed something up.

**Comment by valerionew** [comment]
Fixed by #38
