### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by FFY00** [valerionew/unisolder-notes#4]
Hey, I just have 2 very simple questions.

1) When are you planning to release the case schematics?

2) Can you estimate the overall price of the pcb components?

Thank you for all the work!

**Comment by 5N44P** [comment]
Hi, i'll try to answer as best as i can, but please note that response to number 2 depends on a lot of factors, i'll report my experience and the one from @marcoreps
1. I don't have a schedule at this time. I'm not actively working on it right now, but i plan to come back and finish the lid and the holder, and finally release it. However, if you happen to finish your unisolder before i've released the files. feel free to write me an email or something, and i'll give you a preview/beta of the files.
1. I'd say about 200€, sourced only from legit distributors, with a lot of passives that will remain in your stock. If you go with aliexpress or ebay you may take it to 100€ or less. @marcoreps bought components for 3 boards from official suppliers and spent about 400€ for all three and he still will have some parts left for stock. 
On top of that, you have to add the soldering iron. For now i've only the T245 which costed about another 100€ with one tip.

**Comment by FFY00** [comment]
Thank you for your quick reply. I have been busy so I haven't had the opportunity to reply sooner. I won't be building one for my personal use (yet) because it seems somewhat expensive but I'll maybe build one in college for our hardware hacking group. If that gets approved, I'll probably contact you for the case files. Thank you for all the help :grin:.
